POST http://localhost:8003
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation addUser {
  register(userInfo: { username: "Matija", password: "password", age: 18 }) {
    user {
      username
      password
      firstLetterOfUsername
    }
  }
}
###

// missing authentication
POST http://localhost:8003
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation addUser {
  register(userInfo: { username: "Matija", password: "password", age: 18 }) {
    user {
      username
      password
      firstLetterOfUsername
    }
  }
}

###
POST http://localhost:8003
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation Login {
  login(userInfo:{username:"Matija", password:"$2a$10$hWfN7ILpTAQWWKJblUdW9OZan70bWAILV6NgoVyApUa9JFErLgY4O"})
}

###
// missing authentication
POST http://localhost:8003
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation Login {
  login(userInfo:{username:"", password:"$2a$10$hWfN7ILpTAQWWKJblUdW9OZan70bWAILV6NgoVyApUa9JFErLgY4O"})
}
###

POST http://localhost:8003
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

subscription Registration {
  registrationSuccess {
    username
    password
    admin
    age
    id
  }
}
###

POST http://localhost:8003
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

subscription LoginSubscription {
  loginSuccess
}